# Generated by Django 5.0.4 on 2024-04-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория файла',
                'verbose_name_plural': 'Категории файлов',
            },
        ),
        migrations.CreateModel(
            name='ParentDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер отдела')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название отдела')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Родительский отдел',
                'verbose_name_plural': 'Родительские отделы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Профессия')),
                ('rate', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Ставка')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='ChildDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер отдела')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring_app.parentdepartment', verbose_name='Родительский отдел')),
            ],
            options={
                'verbose_name': 'Подотдел',
                'verbose_name_plural': 'Подотделы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=100, unique=True, verbose_name='Id сотрудника')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring_app.childdepartment', verbose_name='Отдел')),
                ('positions', models.ManyToManyField(to='monitoring_app.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Чистая зарплата')),
                ('dirty_salary', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Грязная зарплата')),
                ('total_salary', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Итогавая зарплата')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='monitoring_app.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Зарплаты',
            },
        ),
    ]
