# Generated by Django 5.0.4 on 2025-09-18 08:33

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_admin_geomap
from django.conf import settings
from django.db import migrations, models

import monitoring_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название учебного места"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Введите широту для отображения на карте",
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Введите долготу для отображения на карте",
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Локация для занятий",
                "verbose_name_plural": "Локации для занятий",
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name="FileCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название шаблона"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Категория файла",
                "verbose_name_plural": "Категории файлов",
            },
        ),
        migrations.CreateModel(
            name="ParentDepartment",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер отдела",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название отдела"
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Родительский отдел",
                "verbose_name_plural": "Родительские отделы",
            },
        ),
        migrations.CreateModel(
            name="PerformanceBonusRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_days",
                    models.PositiveIntegerField(
                        verbose_name="Минимальное количество рабочих дней"
                    ),
                ),
                (
                    "max_days",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное количество рабочих дней"
                    ),
                ),
                (
                    "min_attendance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Минимальный процент посещаемости",
                    ),
                ),
                (
                    "max_attendance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Максимальный процент посещаемости",
                    ),
                ),
                (
                    "bonus_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Бонус (в процентах)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило бонуса",
                "verbose_name_plural": "Правила бонуса",
                "ordering": ["min_days"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Сотрудник", max_length=255, verbose_name="Профессия"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(1), max_digits=4, verbose_name="Ставка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата праздника")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название праздника"),
                ),
                (
                    "is_working_day",
                    models.BooleanField(default=False, verbose_name="Рабочий день"),
                ),
            ],
            options={
                "verbose_name": "Праздничный день",
                "verbose_name_plural": "Праздничные дни",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(max_length=100, verbose_name="Название ключа"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        editable=False, max_length=256, verbose_name="Ключ"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Статус активности"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Ключ",
                "verbose_name_plural": "API Ключи",
            },
        ),
        migrations.CreateModel(
            name="ChildDepartment",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер отдела",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название отдела"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="monitoring_app.childdepartment",
                        verbose_name="Родительский отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подотдел",
                "verbose_name_plural": "Подотделы",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP-адрес")),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время запроса"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог запросов на сброс пароля",
                "verbose_name_plural": "Логи запросов на сброс пароля",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="Токен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "_used",
                    models.BooleanField(
                        default=False, verbose_name="Статус использования"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен для сброса пароля",
                "verbose_name_plural": "Токены для сброса паролей",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Id сотрудника",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("surname", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "date_of_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=monitoring_app.models.user_avatar_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Фото Пользователя",
                    ),
                ),
                (
                    "needs_training",
                    models.BooleanField(default=True, verbose_name="Тренировка модели"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring_app.childdepartment",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "positions",
                    models.ManyToManyField(
                        to="monitoring_app.position", verbose_name="Должность"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Чистая зарплата"
                    ),
                ),
                (
                    "total_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Итоговая зарплата",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Полная занятость"),
                            ("part_time", "Частичная занятость"),
                            ("gph", "ГПХ"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Тип контракта",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="monitoring_app.staff",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зарплата",
                "verbose_name_plural": "Зарплаты",
            },
        ),
        migrations.CreateModel(
            name="RemoteWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "permanent_remote",
                    models.BooleanField(
                        default=False, verbose_name="Постоянная дистанционная работа"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_work",
                        to="monitoring_app.staff",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дистанционная работа",
                "verbose_name_plural": "Дистанционная работа",
            },
        ),
        migrations.CreateModel(
            name="LessonAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=300, verbose_name="Название предмета"),
                ),
                ("tutor_id", models.IntegerField(verbose_name="Id преподавателя")),
                (
                    "tutor",
                    models.CharField(max_length=300, verbose_name="ФИО преподавателя"),
                ),
                ("first_in", models.DateTimeField(verbose_name="Время начала занятия")),
                (
                    "last_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время окончания занятия"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Примерные координаты в радиусе 300 метров",
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Примерные координаты в радиусе 300 метров",
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "date_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата занятия"
                    ),
                ),
                (
                    "staff_image_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Путь к фотографии сотрудника",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_attendance",
                        to="monitoring_app.staff",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещаемость занятия",
                "verbose_name_plural": "Посещаемость занятий",
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name="AbsentReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("business_trip", "Командировка"),
                            ("sick_leave", "Болезнь"),
                            ("other", "Другая причина"),
                        ],
                        max_length=20,
                        verbose_name="Причина отсутствия",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Утверждено"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="absence_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Документ",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="monitoring_app.staff",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уважительная причина отсутствия",
                "verbose_name_plural": "Уважительные причины отсутствия",
            },
        ),
        migrations.CreateModel(
            name="StaffFaceMask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mask_encoding", models.JSONField(verbose_name="Вектор лица")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_mask",
                        to="monitoring_app.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маска лица сотрудника",
                "verbose_name_plural": "Маски лиц сотрудников",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False, verbose_name="Статус Блокировки"
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Последний IP-адрес входа"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_at",
                    models.DateField(
                        editable=False, verbose_name="Дата добавления записи в Таблицу"
                    ),
                ),
                (
                    "first_in",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Время первого входа",
                    ),
                ),
                (
                    "last_out",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Время последнего выхода",
                    ),
                ),
                (
                    "area_name_in",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Зона входа"
                    ),
                ),
                (
                    "area_name_out",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Зона выхода",
                    ),
                ),
                (
                    "absence_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring_app.absentreason",
                        verbose_name="Причина отсутствия",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="monitoring_app.staff",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещаемость сотрудника",
                "verbose_name_plural": "Посещаемость сотрудников",
                "unique_together": {("staff", "date_at")},
            },
        ),
    ]
