# Generated by Django 5.0.4 on 2024-04-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together=set(),
        ),
    ]
