# Generated by Django 5.0.4 on 2024-04-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childdepartment",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
