# Generated by Django 5.0.4 on 2025-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="childdepartment",
            index=models.Index(
                fields=["parent"], name="monitoring__parent__64fc4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childdepartment",
            index=models.Index(fields=["name"], name="monitoring__name_0e6ff9_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["department"], name="monitoring__departm_5e5bfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["pin"], name="monitoring__pin_1afcf6_idx"),
        ),
    ]
