# Generated by Django 5.0.4 on 2024-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='patronymic',
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='Сотрудник', max_length=255, verbose_name='Профессия'),
        ),
    ]
