# Generated by Django 5.0.4 on 2024-04-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='positions',
        ),
    ]
