# Generated by Django 5.0.4 on 2024-07-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childdepartment",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="monitoring_app.parentdepartment",
                verbose_name="Родительский отдел",
            ),
        ),
    ]
