# Generated by Django 5.0.4 on 2024-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffattendance",
            name="first_in",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="Время первого входа",
            ),
        ),
        migrations.AlterField(
            model_name="staffattendance",
            name="last_out",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="Время последнего выхода",
            ),
        ),
    ]
