# Generated by Django 5.0.4 on 2024-04-21 07:01

import django.core.validators
import monitoring_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0002_remove_staff_patronymic_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=monitoring_app.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фото Пользователя'),
        ),
    ]
