# Generated by Django 5.0.4 on 2024-07-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0002_alter_childdepartment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childdepartment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="monitoring_app.childdepartment",
                verbose_name="Родительский отдел",
            ),
        ),
    ]
