# Generated by Django 5.0.4 on 2024-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0002_remove_staff_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='positions',
            field=models.ManyToManyField(to='monitoring_app.position'),
        ),
    ]
