# Generated by Django 5.0.4 on 2026-01-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0002_add_department_staff_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="absentreason",
            index=models.Index(
                fields=["staff", "start_date", "end_date"],
                name="monitoring__staff_i_7a2241_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="absentreason",
            index=models.Index(
                fields=["approved"], name="monitoring__approve_641b73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                fields=["staff", "date_at"], name="monitoring__staff_i_d86704_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                fields=["date_at"], name="monitoring__date_at_8c3651_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                fields=["first_in"], name="monitoring__first_i_d81876_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                fields=["last_out"], name="monitoring__last_ou_bfff4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                fields=["tutor_id"], name="monitoring__tutor_i_48311f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remotework",
            index=models.Index(
                fields=["staff", "start_date", "end_date"],
                name="monitoring__staff_i_32db99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="remotework",
            index=models.Index(
                fields=["permanent_remote"], name="monitoring__permane_7551fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salary",
            index=models.Index(fields=["staff"], name="monitoring__staff_i_c956a7_idx"),
        ),
        migrations.AddIndex(
            model_name="salary",
            index=models.Index(
                fields=["contract_type"], name="monitoring__contrac_b4633e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["staff", "date_at"], name="monitoring__staff_i_9b2ac4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["date_at"], name="monitoring__date_at_45c2ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["first_in"], name="monitoring__first_i_78426a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["last_out"], name="monitoring__last_ou_59b05a_idx"
            ),
        ),
    ]
