# Generated by Django 5.0.4 on 2024-04-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0002_alter_staffattendance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffattendance",
            unique_together={("staff", "date_at")},
        ),
    ]
