# Generated by Django 5.0.4 on 2024-07-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0003_alter_childdepartment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата праздника")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название праздника"),
                ),
            ],
            options={
                "verbose_name": "Праздничный день",
                "verbose_name_plural": "Праздничные дни",
            },
        ),
    ]
