# Generated by Django 5.0.4 on 2024-04-21 08:42

import django.core.validators
import django.db.models.deletion
import monitoring_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0003_staff_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=monitoring_app.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])], verbose_name='Фото Пользователя'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Статус Блокировки')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
