# Generated by Django 5.0.4 on 2024-06-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0003_apikey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"verbose_name": "API Ключ", "verbose_name_plural": "API Ключи"},
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
