# Generated by Django 5.0.4 on 2024-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0004_publicholiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicholiday",
            name="is_working_day",
            field=models.BooleanField(default=False, verbose_name="Рабочий день"),
        ),
    ]
