# Generated by Django 5.0.4 on 2024-04-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0004_alter_staffattendance_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffattendance",
            name="date_at",
            field=models.DateField(
                editable=False, verbose_name="Дата добавления записи в Таблицу"
            ),
        ),
    ]
