# Generated by Django 5.0.4 on 2024-06-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0004_alter_apikey_options_alter_apikey_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
