# Generated by Django 5.0.4 on 2026-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0004_add_classlocation_acceptance_radius_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classlocation",
            name="acceptance_radius_m",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Переопределение: если задано, используется вместо вычисленного по соседям. 20–30 м — кабинет, 50–100 м — здание/двор. Подберите по кругу на карте в админке.",
                null=True,
                verbose_name="Приёмный радиус (м)",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="needs_training",
            field=models.BooleanField(
                default=True, verbose_name="Требуется обучение модели распознавания лиц"
            ),
        ),
    ]
