# Generated by Django 5.0.4 on 2024-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0004_alter_staff_avatar_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pin',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Id сотрудника'),
        ),
    ]
