# Generated by Django 5.0.4 on 2026-01-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0005_alter_classlocation_acceptance_radius_m_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="classlocation",
            index=models.Index(
                fields=["latitude", "longitude"], name="cloc_lat_lon_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classlocation",
            index=models.Index(
                fields=["acceptance_radius_m"], name="cloc_accept_r_idx"
            ),
        ),
    ]
