# Generated by Django 5.0.4 on 2024-07-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0006_remove_userprofile_address_userprofile_last_login_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Полная занятость"),
                    ("part_time", "Частичная занятость"),
                    ("gph", "ГПХ"),
                ],
                default="full_time",
                max_length=20,
                verbose_name="Тип контракта",
            ),
        ),
    ]
