# Generated by Django 5.0.4 on 2026-02-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0006_classlocation_cloc_lat_lon_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                fields=["date_at", "first_in"], name="lsnatt_date_first_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                fields=["staff", "first_in"], name="lsnatt_staff_first_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["date_at", "staff"], name="stfatt_date_staff_idx"
            ),
        ),
    ]
