# Generated by Django 5.0.4 on 2024-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0007_salary_contract_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary",
            old_name="clean_salary",
            new_name="net_salary",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="dirty_salary",
        ),
        migrations.AlterField(
            model_name="salary",
            name="total_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=10,
                null=True,
                verbose_name="Итоговая зарплата",
            ),
        ),
    ]
