# Generated by Django 5.0.4 on 2024-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0008_rename_clean_salary_salary_net_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Статус активности"),
        ),
    ]
