# Generated by Django 5.0.4 on 2026-02-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0009_staffattendance_date_area_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lessonattendance",
            name="lsnatt_lat_lon_first_idx",
        ),
    ]
