# Generated by Django 5.2.11 on 2026-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0010_remove_lessonattendance_lsnatt_lat_lon_first_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonattendance",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="last_out − first_in, заполняется при сохранении.",
                null=True,
                verbose_name="Длительность занятия (сек)",
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="area_sequence",
            field=models.JSONField(
                blank=True,
                help_text="Список {t, area} в хронологическом порядке.",
                null=True,
                verbose_name="Цепочка зон (для карты перемещений)",
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="effective_work_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Сумма интервалов «внутри» по турникетам выхода.",
                null=True,
                verbose_name="Эффективное время в здании (сек)",
            ),
        ),
    ]
