# Generated by Django 5.2.11 on 2026-03-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring_app",
            "0011_add_effective_work_seconds_area_sequence_duration_seconds",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="staffattendance",
            name="effective_work_intervals",
            field=models.JSONField(
                blank=True,
                help_text="Список {start, end} в ISO формате для вычитания пересечений с занятиями.",
                null=True,
                verbose_name="Интервалы «в здании» (для объединения с LA)",
            ),
        ),
    ]
