# Generated by Django 5.2.11 on 2026-03-01 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0012_add_effective_work_intervals"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lessonattendance",
            index=models.Index(
                condition=models.Q(("date_at__gte", datetime.date(2024, 9, 1))),
                fields=["date_at", "staff"],
                name="lsnatt_date_staff_recent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                condition=models.Q(("date_at__gte", datetime.date(2024, 9, 1))),
                fields=["date_at", "staff"],
                name="stfatt_date_staff_recent_idx",
            ),
        ),
    ]
