# Generated by Django 5.2.11 on 2026-03-16 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0013_partial_indexes_recent_attendance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_manual_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Когда выставлен ручной вердикт",
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_manual_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_attendance_manual_verdicts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто выставил ручной вердикт",
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_manual_comment",
            field=models.TextField(
                blank=True, default="", verbose_name="Комментарий ручного вердикта"
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_manual_verdict",
            field=models.CharField(
                choices=[
                    ("none", "Нет ручного вердикта"),
                    ("clean", "Нормальное"),
                    ("suspicious", "Обман"),
                ],
                db_index=True,
                default="none",
                max_length=16,
                verbose_name="Ручной вердикт по фото",
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_spoof_checked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Время последней антифрод проверки",
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_spoof_model_version",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=32,
                verbose_name="Версия антифрод модели",
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_spoof_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Скор антифрод проверки"
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_spoof_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает проверки"),
                    ("clean", "Нормальное"),
                    ("review", "На ручную проверку"),
                    ("suspicious", "Подозрительное"),
                    ("error", "Ошибка проверки"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="Статус антифрод проверки фото",
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_spoof_tags",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Теги антифрод проверки"
            ),
        ),
        migrations.AddField(
            model_name="lessonattendance",
            name="photo_trust_confirmed",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Итог доверия фото (авто)",
            ),
        ),
    ]
