# Generated by Django 5.2.11 on 2026-03-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0014_lessonattendance_photo_manual_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonattendance",
            name="photo_manual_verdict",
            field=models.CharField(
                choices=[
                    ("none", "Нет ручного вердикта"),
                    ("clean", "Нормальное"),
                    ("suspicious", "Подозрительное (ручное)"),
                ],
                db_index=True,
                default="none",
                max_length=16,
                verbose_name="Ручной вердикт по фото",
            ),
        ),
        migrations.AlterField(
            model_name="lessonattendance",
            name="photo_spoof_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает проверки"),
                    ("clean", "Нормальное"),
                    ("review", "На ручную проверку"),
                    ("suspicious", "Подозрительное (авто)"),
                    ("error", "Ошибка проверки"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="Статус антифрод проверки фото",
            ),
        ),
    ]
