# Generated by Django 5.2.11 on 2026-04-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0016_staff_face_profile_and_samples"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="stafffacesample",
            new_name="monitoring__staff_i_5ec9f6_idx",
            old_name="m_app_sfs_staff_act_tr_idx",
        ),
        migrations.RenameIndex(
            model_name="stafffacesample",
            new_name="monitoring__staff_i_785770_idx",
            old_name="m_app_sfs_staff_ang_act_idx",
        ),
    ]
