# Generated by Django 5.2.11 on 2026-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring_app",
            "0017_rename_m_app_sfs_staff_act_tr_idx_monitoring__staff_i_5ec9f6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stafffacesample",
            name="with_glasses",
            field=models.BooleanField(
                default=False,
                help_text="Включите, если в этот момент сотрудник в очках — так эталон лучше совпадает с реальными проходами.",
                verbose_name="На кадре видны очки",
            ),
        ),
    ]
