# Generated by Django 5.2.11 on 2026-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0018_alter_stafffacesample_with_glasses_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Дата, когда сотрудник перестал приходить во внешней выгрузке. Пока поле заполнено, запись заморожена: импорт её не обновляет, посещаемость не загружается, в API и отчёты она не попадает.",
                null=True,
                verbose_name="Исключён из выгрузки",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Сотрудник",
                max_length=255,
                unique=True,
                verbose_name="Профессия",
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["department", "archived_at"],
                name="monitoring__departm_e49c65_idx",
            ),
        ),
    ]
