# Generated by Django 5.2.11 on 2026-09-29 12:43

from django.db import migrations, models


def create_settings(apps, schema_editor):
    apps.get_model("monitoring_app", "AttendanceSettings").objects.get_or_create(
        pk=1, defaults={"turnstile_only": True}
    )


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring_app", "0019_staff_archived_at_alter_position_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "turnstile_only",
                    models.BooleanField(
                        default=True,
                        help_text="Вкл: приход/уход и время в здании считаются только по турникетам (ATTENDANCE_TURNSTILE_DEVICE_SNS); нет турникета — нет на работе. Выкл: берутся все устройства (лифты, ЦОС), последний в выгрузке — уход. История перемещений всегда содержит все устройства. После сохранения отчётные поля пересчитываются в фоне.",
                        verbose_name="Отчёт только по турникетам",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки посещаемости",
                "verbose_name_plural": "Настройки посещаемости",
            },
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="report_variants",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="{'all': {...}, 'turnstile': {...}} — отчётные поля по обоим режимам. first_in/last_out/area_name_*/effective_* = вариант активного режима AttendanceSettings.turnstile_only.",
                null=True,
                verbose_name="Варианты отчёта (все устройства / только турникеты)",
            ),
        ),
        migrations.AlterField(
            model_name="staffattendance",
            name="effective_work_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Сумма интервалов «внутри» по устройствам выхода (с учётом режима отчёта).",
                null=True,
                verbose_name="Эффективное время в здании (сек)",
            ),
        ),
        migrations.RunPython(create_settings, migrations.RunPython.noop),
    ]
