CLASS_LOCATION_ACCEPTANCE_RADII_CACHE_KEY = "class_location_acceptance_radii"
CLASS_LOCATION_ACCEPTANCE_RADII_CACHE_TTL = 3600
CLASS_LOCATION_LIST_CACHE_KEY = "classlocation_list"
CLASS_LOCATION_LIST_CACHE_TTL = 3600
CLASS_LOCATION_CACHE_VERSION_KEY = "class_location_index_version"

PUBLIC_HOLIDAY_LIST_CACHE_KEY = "publicholiday_list"
PUBLIC_HOLIDAY_LIST_CACHE_TTL = 3600

# Radii (m) by neighborhood class
ACCEPTANCE_R_SAME_POINT = 60  # min_d < SAME_POINT_THRESHOLD_M
ACCEPTANCE_R_CLUSTER = 80  # SAME_POINT_THRESHOLD_M ≤ min_d < CLUSTER_THRESHOLD_M
ACCEPTANCE_R_STANDALONE = 70  # min_d ≥ CLUSTER_THRESHOLD_M

# Thresholds (m) to the nearest other location
SAME_POINT_THRESHOLD_M = 5
CLUSTER_THRESHOLD_M = 30

# Fallback if there is no cache entry for the location
DEFAULT_ACCEPTANCE_RADIUS_M = 70
